name: lightrunners
description: A simple Flame game.
version: 0.1.0

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.0
  flame: ^1.8.0
  flame_audio: ^2.0.3
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.2
  gamepads: ^0.1.1
  google_fonts: ^4.0.4
  phased: ^0.0.3

dev_dependencies:
  flame_lint: ^1.0.0
  flame_test: ^1.11.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: false
  shaders:
    - shaders/super_crt.glsl
    - shaders/bloom.glsl
  assets:
    - google_fonts/
    - assets/images/
    - assets/images/ships/
