name: lightrunners
description: A simple Flame game.
version: 0.1.0

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.0
  firebase_admin: ^0.2.0
  firedart: ^0.9.7
  flame: ^1.9.0
  flame_audio: ^2.1.0
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.2
  gamepads: ^0.1.1
  google_fonts: ^4.0.4
  phased: ^0.0.3
  vector_math: ^2.1.4

dev_dependencies:
  flame_lint: ^1.1.1
  flame_test: ^1.13.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: false
  shaders:
    - shaders/super_crt.glsl
  assets:
    - google_fonts/
    - assets/audio/
    - assets/images/
    - assets/images/ships/
    - assets/images/powerups/
