name: flutter_con_game
description: A simple Flame game.
version: 0.1.0

publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flame: ^1.7.3
  flame_audio: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^0.2.0+2
  flame_test: ^1.10.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: false